services:
  api-gateway:
    build: .
    restart: unless-stopped
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

      GATEWAY_JWT_SECRET: ${GATEWAY_JWT_SECRET}
      GATEWAY_JWT_EXPIRES_IN_FALLBACK: ${GATEWAY_JWT_EXPIRES_IN_FALLBACK}

      OPENWEBUI_URL: ${OPENWEBUI_URL}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
    ports:
      - "9090:9090"
